#!/bin/bash
#
SCRIPT_NAME=/ REQUEST_METHOD=GET SERVER_PROTOCOL=HTTP/1.1 QUERY_STRING="ACME_HOOK=add&ACME_DOMAIN=example.com&ACME_KEYAUTH=abc123keyauth" cgi-fcgi -bind -connect 127.0.0.1:9000
SCRIPT_NAME=/ REQUEST_METHOD=GET SERVER_PROTOCOL=HTTP/1.1 QUERY_STRING="ACME_HOOK=remove&ACME_DOMAIN=example.com" cgi-fcgi -bind -connect 127.0.0.1:9000


